### ISSUE TITLE
Associate FluidReview user ids with ecommerce users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#137]
@pdpinch commented on [Wed Nov 15 2017](https://github.com/mitodl/odl-video-service/issues/364)

As a developer, I'd like to be able to make requests for user information from FluidReview via the FluidReview API. However, the FluidReview APIs don't support querying by e-mail address like the old admissions application did. Instead, all requests to the user API must specify a FluidReview user id. 

See http://docs.fluidreview.com/fluidreview/resources/users.html

We can store an external (FluidReview) id on the user or profile? model that we can use for making queries. 

We can get the id one of two ways: either from a webhook executed by FluidReview when a user is accepted into a bootcamp, or by requesting the full list of users via `GET /api/v2/users/`.

**Comment by noisecapella** [comment]
@mbertrand For this issue we should add to `WebhookRequest` all the fields from the schema here: https://github.com/mitodl/bootcamp-ecommerce/issues/136#issuecomment-349000434 except for the date of birth, I'm not sure we need that. The code needs to fail gracefully so that `body` will always contain the webhook data even if parsing failed. We should also add a field `status` to indicate whether we have attempted to parse the data yet and if the parsing went successfully, or if parsing failed. I don't think we should have a `ForeignKey` to user since the user may not exist yet in the system.

**Comment by mbertrand** [comment]
Thanks @noisecapella

**Comment by mbertrand** [comment]
@noisecapella @pdpinch do you think`IntegerField` would be adequate for all the WebhookRequest numeric fields (`submission_id`, `user_id`, `award_id`) or might `BigIntegerField` be necessary?  Not sure what range of values to expect.

Also wondering if there should be validation on the `amount_to_pay` and `award_cost` string values to make sure they can be parsed to valid numbers.

**Comment by noisecapella** [comment]
I can't find any documentation on that and Django's docs say IntegerField should support up to 2 billion, but I think we should assume it won't go past that. If this assumption fails in the future we will have the raw data to reparse with later

**Comment by noisecapella** [comment]
Regarding amount_to_pay and award_cost, there is the possibility that they won't be set at all so we should handle that. FluidReview does allow you to specify the type of metadata so I think we can be reasonably sure that the field won't contain non-numeric input

**Comment by mbertrand** [comment]
I have this working, but needed to modify the OAuth login process to associate users by email instead of username: `social_core.pipeline.social_auth.associate_by_email`.  

If a User doesn't yet exist when a Webhook request (or batch FluidReview user import) comes in, it will be created with username == email address (and a profile object as well, with the FluidReview user id stored there in a new field).  

However, user objects created when someone logs in via EdX have username == OAuth username (for instance `mattbert` instead of `mattbert@mit.edu`).  @pdpinch should the username of a webhook-generated user be changed to the OAuth username when that person logs in?  Or keep it as originally created (equal to the email)?
