### ISSUE TITLE
Unable to segment and email nurture incomplete round 1 applicants 

### ISSUE THREAD

**Issue by ChrisLanfranco** [mitodl/bootcamp-ecommerce#330]
We (bootcamps/marketing) would like to be able to send emails to those applicants who have started, but not finished their round 1 applications for bootcamps, by the specific bootcamp they are in process with.

At this time, a deal/product is only created when they complete round 1 of their application.

<img width="400" alt="Screen Shot 2020-01-24 at 10 54 32 AM" src="https://user-images.githubusercontent.com/22057324/73599642-a1d4e280-4513-11ea-966e-2501543cdea3.png">

Could it be possible to create deal/product on clicking the apply button of a bootcamp?

TY!
Chris

**Comment by pdpinch** [comment]
I met with Mariah on Monday and we were able to add a new trigger to SMApply that fires when the application is _started_. Prior to this, all the triggers were only firing when the user completed an application stage. 

This had the affect of setting the stage to "Round 1" in hubspot for Mariah's test user. 

As far as I know, this issue is fixed now.

**Comment by pdpinch** [comment]
It looks like this didn't work as well as I hoped, probably because of #332

**Comment by pdpinch** [comment]
Hi Chris. Sorry for the delay in follow-up, but this should have been fixed as of 3/6. We alerted Mariah, but I don't know if she has been able to test any further yet. 

closed by #350
