### ISSUE TITLE
UI: Specify success, error, and loading behaviors for pages that make HTTP requests

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#641]
We have a bunch of UI elements that make HTTP requests either upon page load or in response to a button click et. al. We need to decide on what happens when those requests fail, and when certain requests succeed.

#### Specific questions to answer:
- For a page/component that makes a request for data as soon as it loads or after a button click, what happens if that request fails? Examples: the application dashboard page loading a user's applications, the new application form loading all available bootcamp runs, the admin review list page loading all user submissions that need review.
  - Option(s) - We could have show a standard error component in the body of each page with some meaningful text. This would be shown instead of the normal page contents. We could also use a toast message.
- What should happen in general when a request to create/update something succeeds? Examples: creating a new application via the form, successfully completing a payment, submitting a review for an application in the admin review page.
  - Option(s) - This seems like a good use case for a toast message. Regardless of the UI element we use, I assume that a new application/successful payment should simply close the drawer and remain on the application dashboard, and the review should send the user back to the review list page.
- What should happen when a request to create/update something fails? Same examples as above.
  - Option(s) - Show a simple error message near the submit button and keep the user on the same page. We could also use a toast.
- Should we have any standard UI effect when a request to create/update something is in progress? 
  - Option(s) - Replace button contents with a spinner, replace the entire button with a spinner, put a spinner next to the button, simply set the button to disabled and grey it out
- Should we have any standard UI effect when a request to load some data is in progress? Examples: loading a page of submissions in the admin review list page, loading application details when the "expand" button is clicked in the application dashboard

**Comment by abdulkdawson** [comment]
We have a bunch of UI elements that make HTTP requests either upon page load or in response to a button click et. al. We need to decide on what happens when those requests fail, and when certain requests succeed.

#### Specific questions to answer:
- For a page/component that makes a request for data as soon as it loads or after a button click, what happens if that request fails? Examples: the application dashboard page loading a user's applications, the new application form loading all available bootcamp runs, the admin review list page loading all user submissions that need review.
  - Option(s) - We could have show a standard error component in the body of each page with some meaningful text. This would be shown instead of the normal page contents. We could also use a toast message.

**I think a toast message here would work.**

- What should happen in general when a request to create/update something succeeds? Examples: creating a new application via the form, successfully completing a payment, submitting a review for an application in the admin review page.

**We could also apply a toast message with success or confirmation text.**

  - Option(s) - This seems like a good use case for a toast message. Regardless of the UI element we use, I assume that a new application/successful payment should simply close the drawer and remain on the application dashboard, and the review should send the user back to the review list page.

**I Agree**

- What should happen when a request to create/update something fails? Same examples as above.
  - Option(s) - Show a simple error message near the submit button and keep the user on the same page. We could also use a toast message.

**An error message near the submit button would be best.** 

- Should we have any standard UI effect when a request to create/update something is in progress? 
  - Option(s) - Replace button contents with a spinner, replace the entire button with a spinner, put a spinner next to the button, simply set the button to disabled and grey it out

**Replacing the button with a spinner works for me.**

- Should we have any standard UI effect when a request to load some data is in progress? Examples: loading a page of submissions in the admin review list page, loading application details when the "expand" button is clicked in the application dashboard

**We could use a spinner where the content would be.**
