### ISSUE TITLE
Homepage:  margins in the title and description in the bootcamp grid

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#708]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/430126/85167626-1e542d80-b237-11ea-8d9a-e4e459cdb2a1.png">

Compare to the design at https://projects.invisionapp.com/d/main?origin=v7#/console/19950477/418712140/preview?scrollOffset=0

**Comment by gsidebo** [comment]
@abdulkdawson On RC it looks like these content sections underneath the bootcamp images still have a left margin: https://bootcamp-rc.odl.mit.edu/. Can you review that and confirm that those should be there? If so, we can close this issue. If not, we can get someone working on it

**Comment by abdulkdawson** [comment]
@gsidebo the content beneath the images should have a left margin of 30px. So yes there should be a left margin but no more than 30px.

**Comment by gsidebo** [comment]
@abdulkdawson Those white squares at the bottom left of those "X" placeholder images is about 60x60px. On the left side, the content is indented to be aligned with the edge of the white square, so that would be a 60px left margin. Those white squares are implemented on the site, and the content is lined up with the right edge of those squares like the designs. Do you want to (a) make those squares 30x30, (b) leave the squares unchanged and make the left margins 30px anyway, or (c) get rid of those white squares?
