### ISSUE TITLE
BI: add recognition report

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#782]
Originally introduced in this issue: https://github.com/mitodl/bootcamp-ecommerce/issues/695

See [RFC](https://docs.google.com/document/d/1uqzstrv7gB9XdOfopSk6AEJGQDo_78x4UafRXIVWIhA/edit) for details

**Comment by pdpinch** [comment]
@abeglova some feedback:

- [ ] Can you add this RC report to the [Bootcamp RC dashboard](https://bi.odl.mit.edu/dashboard/bootcamps)?
- [ ] Please change the title of the report to match the other RC reports, i.e. "Bootcamps (RC) - Recognition" 
- [ ] Can you display the username instead of the user_id? 
- [ ] I'm not seeing any values for Application ID
- [ ] I'm not seeing any values for First and Last name
- [ ] How are you calculating `attendance_status`? What is `klasses_bootcamprunenrollment.active` ? 
- [ ] I think it would be easier to read if `personal_price` came after `total_paid` and before `list_price`

**Comment by abeglova** [comment]
I don't think I have access to edit Bootcamp RC dashboard?

**Comment by abeglova** [comment]
There is a `klasses_bootcamprunenrollment` and `klasses_bootcamprunenrollment.active` is True for currently enrolled students. For students who drop out of the bootcamp `active`=False and `change_status` is populated. Right now `change_status` can only be null or  "refunded"

**Comment by abeglova** [comment]
Looks like I don't have permissions to add to the RC dashboard, unless I'm missing something in the UI.
Here is a link to the report
https://bi.odl.mit.edu/queries/977/source#1688

**Comment by pdpinch** [comment]
I'm having trouble reviewing this because the data on RC is so sketchy. Can you make a version with production data?

**Comment by abeglova** [comment]
Done https://bi.odl.mit.edu/queries/992
