### ISSUE TITLE
Remove obsolete error handling in UploadResumeView

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#919]
https://github.com/mitodl/bootcamp-ecommerce/blob/master/applications/views.py#L204-L206

**Comment by gsidebo** [comment]
**NOTE:** Unless we have some sensible error text for this case that I'm not able to think of right now, this try/except should be completely removed and we should just let the exception go uncaught. The "application state" is not a meaningful concept to our users and it will only cause confusion. We will want to be alerted via Sentry in these cases anyway since they should not be possible. #906 adds error messages in cases where we get a 500 back from the server, and #901 covers the work to show a sensible/more visible message if an upload fails, so this custom error message should not be necessary
